### PR TITLE
Hatchery: Add UnlockMegaEvolutions setting

### LINKED ISSUE #201: Hatchery: Focus on mega-evolvable pokemon with missing requirements
### Is your feature request related to a problem? Please describe.
The new megaevolutions add an attack requirement to do the megaevolution. This means that the pokemon needs to be focused in the hatchery over other things

### Describe the solution you'd like
Add an option in the hatchery to focus on pokemon that can megaevolve but dont have the requirement yet

### PR DESCRIPTION
**Pull request by Farigh**
The mega evolutions have an minimum base attack increase requirement.
This new option will breed pokemon that do not match such requirement in priority.

Fixes #201

### CODE REVIEW

**Comment by Farigh** [comment]
I'll try to add an automated test for this filter before merging

**Comment by Daniferrito** [comment]
This looks good as it is. It will break if they add some other requirement to the megaevolution, as it will keep breeding the pokemon after it has the required attack, but if that even happens it will have to be fixed then.

**Comment by Farigh** [comment]
I tested the focus by insuring the unwanted crops were harvested as soon as possible and that planting strategy worked properly.
The other parts of this mechanic should be guaranteed by unit tests.

**Comment by Farigh** [comment]
I used the MegaEvolutionRequirements instead of an hard-coded 100 times check to prevent such case, we should be fine, unless they revamp this entirely ;)

**Pull request merged**
