### PR TITLE
BattleFrontier: Add the battle frontier automation

### LINKED ISSUE #150: Implement automation in Battle Frontier
Something simple like entering a loop of starting the Battle Frontier over and over every time you reach the maximum possible.
This to complete Quest and to get Battle Points.

### PR DESCRIPTION
**Pull request by Daniferrito**
It is very simple. If the battle frontier finishes, it restarts it. If the player manually left it, it disables itself.

No other logic to it

Edit: Implements (part) of #150 

Fixes #150

### CODE REVIEW

**Review by Farigh — APPROVED** [review]
Looks good to me.

I removed an internal var that was not used and stored the panel container so we don't have to use `document.getElementById` anymore

I renamed the `Auto fight` to `Auto start`, which seemed more appropriate

Thanks for your contribution

**Comment by Farigh** [comment]
Let's close the issue, if an improvement is requested, we'll create a new one

Fixes #150

**Comment by Daniferrito** [comment]
> I removed an internal var that was not used
Oh, yea, I removed the need for it, but forgot to delete the declaration, sorry.

> stored the panel container
Might want to do the same with Gym then. This is basically the Gym code but specialized for Battle Frontier.

> renamed
Yea, that sounds better

**Comment by Farigh** [comment]
> Might want to do the same with Gym then. This is basically the Gym code but specialized for Battle Frontier.

I definitely will do it at some point, didn't fill like bothering right now 😅

**Pull request merged**
