### PR TITLE
Hatchery: Add custom sorting and ordering

### LINKED ISSUE #48: Hatchery: Add the ability to choose the sorting attribute
### Is your feature request related to a problem? Please describe.
In some cases, the player might want to focus on breeding a particular pokemon type.
The current implementation only allows breeding efficiency sorting and shiny pokemon filtering.

### Describe the solution you'd like
Add a dedicated menu for hatchery where the player can fine-tune the breeding parameters.

### Additional context
Suggested by #43

---

Todo:

- [X] ~Prioritize by type~ (#129)
- [ ] Prioritize by EVs
- [X] ~Prioritize by region~ (#114)
- [X] ~Prioritize by regional debuff~ (#114)
- [ ] Sort by other properties than Breeding efficiency

### PR DESCRIPTION
**Pull request by Daniferrito**
Fixes #48 (or at least the part to "Sort by other properties than Breeding efficiency". EVs is also included in the list of attributes, but it might not be what is wanted for it)

### CODE REVIEW

**Comment by Daniferrito** [comment]
I just added the other half of #48, or at least as I understaund it

**Comment by Daniferrito** [comment]
Copying the latest commit message here:

This will make it so if a shiny dex is almost complete (focusing on Kanto, consider shiny last) the auto-hatchery will hatch non-shinies of other regions before repeating already-shinies of Kanto.

Really small optimization, but while focussing on Articuno, Dragonite, and Mewtwo (the only ones I have left), there is no need to keep hatching Gyarados and Pikachus, might as well try for some other non-shinies

**Comment by Daniferrito** [comment]
Added my last suggestion from #197 (consider alternate forms last)

If this is too many options for the UI, feel free to remove the last commit.

**Comment by Farigh** [comment]
I did some improvements to your work.

I'm not willing to change the filter order, so I removed this commit.
I want to be able to reorder all settings, not just the shiny or alternate forms. 
I did not find the time yet to implement a drad and drop reorder mechanism, but as soon as I get the time, Ill do it for this purpose.

I removed the EV one as well and used the in-game setting instead, we should not diverge from that.

**Review by Farigh — APPROVED** [review]

**Comment by Farigh** [comment]
Thanks again for your work :)

**Pull request merged**
